version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    ports:
      - "80:80"
    environment:
      BUZZWORDS_URL: http://buzzwords:3000
    depends_on:
      buzzwords:
        condition: service_healthy
  mongo:
    image: mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    environment:
        - MONGO_INITDB_DATABASE=buzzwords
  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
  rabbitmq:
    image: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
  buzzwords:
    init: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthcheck" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    build:
      context: .
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - RUST_LOG=buzzwords=trace,tower_http=trace
      - MONGO_URL=mongodb://mongo:27017/buzzwords
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3000